apiVersion: v2
name: kube-prometheus-stack-config
description: Kube Prometheus Stack configuration for red-infrastructure
type: application
version: 0.1.0
appVersion: "0.70.0"

dependencies:
  - name: kube-prometheus-stack
    version: "65.1.1"
    repository: "https://prometheus-community.github.io/helm-charts"