# Vault Secrets Management Application
# This manages Vault secret configurations and integrations
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/infra-red-org/red-infrastructure-gitops
    targetRevision: HEAD
    path: red-apps/k8s-manifests
    directory:
      include: "vault-*.yaml"
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: "batch"
      kind: Job
      jsonPointers:
        - /status
        - /metadata/annotations
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /metadata/annotations
    - group: ""
      kind: Secret
      jsonPointers:
        - /metadata/annotations