# Vault Secrets Operator Configuration
# This provides a more robust way to manage secrets from Vault

---
# VaultAuth resource for Kubernetes authentication
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: keda-auth
  namespace: keda
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: keda
    serviceAccount: keda-operator
    audiences:
      - vault

---
# VaultStaticSecret for GCP configuration
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gcp-config
  namespace: keda
spec:
  type: kv-v2
  mount: secret
  path: gcp/project
  destination:
    name: gcp-config
    create: true
  refreshAfter: 30s
  vaultAuthRef: keda-auth

---
# VaultStaticSecret for KEDA configuration
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keda-config
  namespace: keda
spec:
  type: kv-v2
  mount: secret
  path: keda/config
  destination:
    name: keda-config
    create: true
  refreshAfter: 30s
  vaultAuthRef: keda-auth

---
# Example of how to use the secrets in a deployment
apiVersion: v1
kind: ConfigMap
metadata:
  name: keda-deployment-example
  namespace: keda
data:
  example-deployment.yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: keda-example-app
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: keda-example
      template:
        metadata:
          labels:
            app: keda-example
          annotations:
            # Vault agent injection
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/role: "keda"
            vault.hashicorp.com/agent-inject-secret-config: "secret/data/keda/config"
        spec:
          serviceAccountName: keda-operator-vault
          containers:
          - name: app
            image: nginx:alpine
            env:
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: gcp-config
                  key: project_id
            - name: GCP_REGION
              valueFrom:
                secretKeyRef:
                  name: gcp-config
                  key: region