apiVersion: v2
name: traefik-config
description: Traefik configuration for red-infrastructure
type: application
version: 0.1.0
appVersion: "3.0"

dependencies:
  - name: traefik
    version: "36.3.0"
    repository: "https://traefik.github.io/charts"